services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - ELASTIC_PASSWORD=NICOLAS123@@@
      - discovery.type=single-node
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      - ES_JAVA_OPTS=-Xms8g -Xmx8g  # Allocate 8GB of heap memory for Elasticsearch
    networks:
      - elastic-net
    ports:
      - "9200:9200"  # Expose Elasticsearch on port 9200
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data  # Persist Elasticsearch data
    deploy:
      restart_policy:
        condition: on-failure  # Restart container on failure
        delay: 5s
        max_attempts: 3
        window: 120s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=NICOLAS123@@@
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=trial
    networks:
      - elastic-net
    ports:
      - "5601:5601"  # Expose Kibana on port 5601
    depends_on:
      elasticsearch:
        condition: service_started  # Kibana will wait for Elasticsearch to start

volumes:
  elasticsearch_data:  # Persistent volume for Elasticsearch data

networks:
  elastic-net:
    external: true  # Use an existing network
