COLUMNS_TO_WATCH = ["PA_CODUNI",
                    "PA_UFMUN",
                    "PA_CNPJCPF",
                    "PA_CNPJMNT",
                    "PA_CMP",
                    "PA_PROC_ID",
                    "PA_TPFIN",
                    "PA_SUBFIN",
                    "PA_AUTORIZ",
                    "PA_CIDPRI",
                    "PA_CIDSEC",
                    "PA_CATEND",
                    "PA_QTDPRO",
                    "PA_QTDAPR",
                    "PA_VALPRO",
                    "PA_VALAPR",
                    ]

state_codes = {
    "Rondônia": 11,
    "Acre": 12,
    "Amazonas": 13,
    "Roraima": 14,
    "Pará": 15,
    "Amapá": 16,
    "Tocantins": 17,
    "Maranhão": 21,
    "Piauí": 22,
    "Ceará": 23,
    "Rio Grande do Norte": 24,
    "Paraíba": 25,
    "Pernambuco": 26,
    "Alagoas": 27,
    "Sergipe": 28,
    "Bahia": 29,
    "Minas Gerais": 31,
    "Espírito Santo": 32,
    "Rio de Janeiro": 33,
    "São Paulo": 35,
    "Paraná": 41,
    "Santa Catarina": 42,
    "Rio Grande do Sul": 43,
    "Mato Grosso do Sul": 50,
    "Mato Grosso": 51,
    "Goiás": 52,
    "Distrito Federal": 53,
    "Ignorado/exterior": 0
}


FINANC_CODES = {
    "Atenção Básica (PAB)": 1,
    "Assistência Farmacêutica": 2,
    "Fundo de Ações Estratégicas e Compensações FAEC": 4,
    "Incentivo - MAC": 5,
    "Média e Alta Complexidade (MAC)": 6,
    "Vigilância em Saúde": 7,
    "Gestão em Saúde": 8,
}


FAECTP_CODES = {
    1: "Atenção Básica (PAB)",
    2: "Assistência Farmacêutica",
    3: "FAEC - Subtipo de financiamento ignorado",
    4: "Coleta de material",
    5: "Diagnóstico em laboratório clínico",
    6: "Coleta/exame anátomo-patológico colo uterino",
    7: "Diagnóstico em neurologia",
    8: "Diagnóstico em otorrinolaringologia/fonoaudiologia",
    9: "Diagnóstico em psicologia/psiquiatria",
    10: "Consultas médicas/outros profissionais de nível superior",
    11: "Atenção domiciliar",
    12: "Atendimento/acompanhamento em reabilitação física, mental, visual, auditiva e múltiplas deficiências",
    13: "Atendimento/acompanhamento psicossocial",
    14: "Atendimento/acompanhamento em saúde do idoso",
    15: "Atendimento/acompanhamento de queimados",
    16: "Atendimento/acompanhamento de diagnóstico de doenças endocrinas/metabólicas e nutricionais",
    17: "Tratamento de doenças do sistema nervoso central e periférico",
    18: "Tratamento de doenças do aparelho da visão",
    19: "Tratamento em oncologia",
    20: "Nefrologia",
    21: "Tratamentos odontológicos",
    22: "Cirurgia do sistema nervoso central e periférico",
    23: "Cirurgias de ouvido, nariz e garganta",
    24: "Deformidade labio-palatal e crânio-facial",
    25: "Cirurgia do aparelho da visão",
    26: "Cirurgia do aparelho circulatório",
    27: "Cirurgia do aparelho digestivo, orgãos anexos e parede abdominal(inclui pré e pós operatório)",
    28: "Cirurgia do aparelho geniturinário",
    29: "Tratamento de queimados",
    30: "Cirurgia reparadora para lipodistrofia",
    31: "Outras cirurgias plásticas/reparadoras",
    32: "Cirurgia orofacial",
    33: "Sequenciais",
    34: "Cirurgias em nefrologia",
    35: "Transplantes de orgãos, tecidos e células",
    36: "Medicamentos para transplante",
    37: "OPM auditivas",
    38: "OPM em odontologia",
    39: "OPM em queimados",
    40: "OPM em nefrologia",
    41: "OPM para transplantes",
    42: "Incentivos ao pré-natal e nascimento",
    43: "Incentivo ao registro cívil de nascimento",
    44: "Central Nacional de Regulação de Alta Complexidade (CNRAC)",
    45: "Reguladores de Atividade hormonal - Inibidores de prolactina",
    46: "Política Nacional de Cirurgias Eletivas",
    47: "Redesignação e Acompanhamento",
    48: "Projeto Olhar Brasil",
    49: "Mamografia para Rastreamento",
    50: "Projeto Olhar Brasil - Consulta",
    51: "Projeto Olhar Brasil - Óculos",
    52: "Implementar Cirg. CV Pediátrica",
    53: "Cirurgias Eletivas - Componente I",
    54: "Cirurgias Eletivas - Componente II",
    55: "Cirurgias Eletivas - Componente III",
    56: "Prótese Mamária - Exames",
    57: "Prótese Mamária - Cirurgia",
    58: "Transplante - Histocompatibilidade",
    59: "Triagem Neonatal",
    60: "Controle de qualidade do exame citopatológico do colo de útero",
    61: "Exames do Leite Materno",
    62: "Atenção as Pessoas em Situação de Violência Sexual",
    63: "Sangue e Hemoderivados",
    64: "Mamografia para rastreamento em faixa etária recomendada",
    65: "Doenças Raras",
    66: "Cadeiras de Rodas",
    67: "Sistema de Frequencia Modulada Pessoal-FM",
    68: "Medicamentos em Urgência",
    69: "Cirurgias Eletivas - Componente Único",
    70: "Atenção Especializada em Saúde Auditiva",
    71: "Terapias Especializadas em Angiologia",
    72: "Tratamento de Doença Macular",
    73: "OPME Não Relacionados ao Ato Cirúrgico",
    74: "Diagnóstico/tratamento em oncologia",
    75: "Diagnóstico de trombofilia em gestante",
    76: "Reabilitação Pós-COVID-19",
    77: "Telemedicina em Urgência",
    78: "Fisioterapia Cardiovascular",
    79: "Hemodinâmica em atendimento de urgência",
    80: "Exames Sorológicos e Imunológicos",
    81: "FAEC CNRAC (21012-cód ant à tab unif-vál p/2008-01)",
    82: "FAEC Eletiv(21014-cód ant à tab unif-vál p/2008-01)",
    83: "Incentivo - MAC",
    84: "Média e Alta Complexidade (MAC)",
    85: "Vigilância em Saúde",
    86: "Gestão do SUS",
}


def get_mapped_value(code, mapping, default="Unknown"):
    """Helper function to get mapped value from a dictionary."""
    try:
        return mapping.get(int(code), default)
    except ValueError:
        return default


print('pa_subfin', get_mapped_value('1', FAECTP_CODES))

CARATEND_CODES = {
    1: "Eletivo",
    2: "Urgência",
    3: "Acidente no local trabalho ou a serv da empresa",
    4: "Acidente no trajeto para o trabalho",
    5: "Outros tipo de acidente de trânsito",
    6: "Out tp lesões e envenen por agent quím físicos",
}
