COLUMNS_TO_WATCH = ["PA_CODUNI",
                    "PA_UFMUN",
                    "PA_CNPJCPF",
                    "PA_CNPJMNT",
                    "PA_CMP",
                    "PA_PROC_ID",
                    "PA_TPFIN",
                    "PA_SUBFIN",
                    "PA_AUTORIZ",
                    "PA_CIDPRI",
                    "PA_CIDSEC",
                    "PA_CATEND",
                    "PA_QTDPRO",
                    "PA_QTDAPR",
                    "PA_VALPRO",
                    "PA_VALAPR",
                    ]

state_codes = {
    "Rondônia": 11,
    "Acre": 12,
    "Amazonas": 13,
    "Roraima": 14,
    "Pará": 15,
    "Amapá": 16,
    "Tocantins": 17,
    "Maranhão": 21,
    "Piauí": 22,
    "Ceará": 23,
    "Rio Grande do Norte": 24,
    "Paraíba": 25,
    "Pernambuco": 26,
    "Alagoas": 27,
    "Sergipe": 28,
    "Bahia": 29,
    "Minas Gerais": 31,
    "Espírito Santo": 32,
    "Rio de Janeiro": 33,
    "São Paulo": 35,
    "Paraná": 41,
    "Santa Catarina": 42,
    "Rio Grande do Sul": 43,
    "Mato Grosso do Sul": 50,
    "Mato Grosso": 51,
    "Goiás": 52,
    "Distrito Federal": 53,
    "Ignorado/exterior": 0
}
